project:
  type: website

website:
  title: "Klock Saxophone Quartet"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - ourwork.qmd
      - contact.qmdss

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

