project:
  type: website

website:
  title: "Klock Saxophone Quartet"
  twitter-card: true
  favicon: logo.png
  open-graph: true

  navbar:
    title: "Klock Saxophone Quartet"
    search: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - ourwork.qmd
      - contact.qmd

format:
  html:
    theme: lux
    css: styles.css
    font-google:
      - family: Inter
        weights: [400,700]
      - family: Montserrat
        weights: [300,400,700]
      - family: Roboto
        weights: [400,700]

editor: visual

