project:
  type: website

website:
  title: "Klock Saxophone Quartet"
  twitter-card: true
  favicon: logo.png
  open-graph: true

  navbar:
    title: "Klock Saxophone Quartet"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - ourwork.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    font-google: 
      - family: Montserrat
        weights: [300]   # Light weight
    toc: true

editor: visual

