project:
  type: website

website:
  title: "Klock Saxophone Quartet"
  twitter-card: true
  favicon: logo.png
  open-graph: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - ourwork.qmd
      - contact.qmd

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

