---
title: "Klock Quartet"
---

The Klock Quartet

**Lynn Klock** (born August 12, 1950)^[\[1\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-saxhist-1)^ is an American classical saxophonist and educator. He is Principal Saxophone of the [Springfield Symphony Orchestra](https://en.wikipedia.org/wiki/Springfield_Symphony_Orchestra "Springfield Symphony Orchestra") in [Springfield, Massachusetts](https://en.wikipedia.org/wiki/Springfield,_Massachusetts "Springfield, Massachusetts").

## Teaching career

\[[edit](https://en.wikipedia.org/w/index.php?title=Lynn_Klock&action=edit&section=1 "Edit section: Teaching career")\]

From 1980 until his retirement in 2014, Lynn Klock was Professor of Saxophone at the [University of Massachusetts Amherst](https://en.wikipedia.org/wiki/University_of_Massachusetts_Amherst "University of Massachusetts Amherst"). He had previously taught saxophone at the Interlochen National Music camp, [The Hartt School](https://en.wikipedia.org/wiki/The_Hartt_School "The Hartt School"), [University of Toledo](https://en.wikipedia.org/wiki/University_of_Toledo "University of Toledo"), and [Olivet College](https://en.wikipedia.org/wiki/Olivet_College "Olivet College"). Since 1992, he has been a clinician for the Bands of America National Concert Band Festival and Summer Camp. He is a graduate of the University of Michigan and the Interlochen Arts Academy, and was a student of [Larry Teal](https://en.wikipedia.org/wiki/Larry_Teal "Larry Teal"), [Donald Sinta](https://en.wikipedia.org/wiki/Donald_Sinta "Donald Sinta"), Jack Kripl, and [William D. Revelli](https://en.wikipedia.org/wiki/William_D._Revelli "William D. Revelli").^[\[2\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-cb-2)^

Klock's former students include Lisa Osland (Professor of Saxophone and Director of Saxophone Ensembles at the [University of Kentucky](https://en.wikipedia.org/wiki/University_of_Kentucky "University of Kentucky")),^[\[3\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-3)^ Sarah Markham (Saxophone teacher at the Junior department of the [Royal College of Music](https://en.wikipedia.org/wiki/Royal_College_of_Music "Royal College of Music"), and the Universities of [Huddersfield](https://en.wikipedia.org/wiki/University_of_Huddersfield "University of Huddersfield") and [Sheffield](https://en.wikipedia.org/wiki/University_of_Sheffield "University of Sheffield")),^[\[4\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-4)^ David Jenkins ("Presidents Own" [United States Marine Band](https://en.wikipedia.org/wiki/United_States_Marine_Band "United States Marine Band")),^[\[5\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-5)^ George Weremchuk (Assistant Professor of Saxophone at the [University of Central Florida](https://en.wikipedia.org/wiki/University_of_Central_Florida "University of Central Florida")), Michael Sakash (Associate Professor of Music at [Washington & Jefferson College](https://en.wikipedia.org/wiki/Washington_%26_Jefferson_College "Washington & Jefferson College")),^[\[6\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-6)^ David Pope (Professor of Saxophone at [James Madison University](https://en.wikipedia.org/wiki/James_Madison_University "James Madison University")),^[\[7\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-7)^ Brian Sacawa (U.S. Army Field Band), Wayne Tice (United States Military Academy Band, and Rick Hirsch (composer), ^[\[8\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-8)^ and Evan Doyle (Director of Bands at [Westborough High School (Massachusetts)](https://en.wikipedia.org/wiki/Westborough_High_School_(Massachusetts) "Westborough High School (Massachusetts)")).

## Performance career

\[[edit](https://en.wikipedia.org/w/index.php?title=Lynn_Klock&action=edit&section=2 "Edit section: Performance career")\]

Lynn Klock gave his [Carnegie Hall](https://en.wikipedia.org/wiki/Carnegie_Hall "Carnegie Hall") debut in 1978,^[\[1\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-saxhist-1)[\[9\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-9)[\[10\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-10)^ where he premiered a composition by Andrzej Dutkiewicz.^[\[11\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-11)^ He has been a guest soloist with several professional orchestras and bands including the Springfield Symphony Orchestra, New Hampshire Symphony Orchestra, Belgian Air Force Band, West Point Band, and numerous university, community, and high school bands. He has been a soloist or clinician at the English Saxophone Congress (Cardiff, Wales), MENC National Conference, Midwest Band and Orchestra Clinic, CBDNA National Conference, Texas Bandmasters Association Conference, and Western International Band Clinic. In June 2008, he was a guest artist at the 18th Three Rivers Saxophone Quartet Workshop which took place at California University of Pennsylvania.

Works written for Lynn Klock include a work by recent Pulitzer Prize winner [Lewis Spratlan](https://en.wikipedia.org/wiki/Lewis_Spratlan "Lewis Spratlan"). Other composers include [Pulitzer Prize](https://en.wikipedia.org/wiki/Pulitzer_Prize "Pulitzer Prize") winning composers including [Gunther Schuller](https://en.wikipedia.org/wiki/Gunther_Schuller "Gunther Schuller"), [John Harbison](https://en.wikipedia.org/wiki/John_Harbison "John Harbison"), and [Michael Colgrass](https://en.wikipedia.org/wiki/Michael_Colgrass "Michael Colgrass") as part of the World Wide Commissioning Project.^[\[2\]](https://en.wikipedia.org/wiki/Lynn_Klock#cite_note-cb-2)^

## Personal life

\[[edit](https://en.wikipedia.org/w/index.php?title=Lynn_Klock&action=edit&section=3 "Edit section: Personal life")\]

Lynn is married to French hornist Laura Klock, who also taught at the [University of Massachusetts Amherst](https://en.wikipedia.org/wiki/University_of_Massachusetts_Amherst "University of Massachusetts Amherst"). He has a very intricate model railroad in his basement. The railroad is highly detailed with a double track helix, allowing for point to point multiple through train and switching operation, or continuous running of a single train. A full operating session takes about 3 hours and requires several yard masters.
